### PR TITLE
Add event ThanksForPosts.delete_thanks_before

### PR DESCRIPTION
**Pull request by marcovo**
Some users requested a link between the [hide] BBCode extension and the ThanksForPosts extension. This event would be required to accomplish that. (A thanks may not be deleted if a [hide] bbcode is present in a message.)
Request: https://www.phpbb.com/community/viewtopic.php?p=13917886#p13917886
Intended usage: https://github.com/marcovo/phpbb_hidebbcode/blob/master/event/listener.php#L70

### CODE REVIEW

**Comment by lavigor** [comment]
@marcovo, I think that your event should have the vendor prefix (`gfksx.` in this case).
And also globals shouldn't be used here.
Please add `@dispatcher` to the configuration of this helper. =)

Also please see the Travis status, whitespaces are redundant.

Example can be found [here](https://github.com/rxu/posts_merging/blob/master/config/services.yml).

**Comment by marcovo** [comment]
Should it? I wasn't aware of any rules about this... :P . I didn't want to make too many changes so therefore I put the global in it; otherwise one has to get the object via the 'good' way which includes more changes... But well it's possible for sure.

I also wasn't aware of any rules about whitespaces.. By default I always keep my indentation levels consistent, which indeed means extra whitespace... apparently that's not the way to go here :P .

**Comment by lavigor** [comment]
If you need any help with this event, tell me and I'll create another PR for it.:wink:

**Comment by marcovo** [comment]
Well I should be able to do it; I'm only searching for guidelines for the prefix. I only find it should be unique, and consisting of lowercase letters and underscores (which, I admit, I also failed to do :P ) . Also see https://wiki.phpbb.com/Add_Events .

**Comment by lavigor** [comment]
Yes.
I've found the guideline for you (it can also be found somewhere else):
https://area51.phpbb.com/docs/dev/31x/extensions/tutorial_basics.html#triggering-an-event-advanced
> You must always prefix your event names with your vendor and extension name.

**Comment by lavigor** [comment]
@rxu, I think this is fine now. =)

**Comment by Galixte** [comment]
Hi @marcovo & @lavigor,

i have tested this, disabled the extension, update those two files ```config/services.yml``` & ```core/helper.php```, re-activated the extension. It’s result a blank screen just after click on the valide button to re-activate

**Comment by marcovo** [comment]
I guess you should also purge the cache. The services.yml file is cached IIRC. Probably after you re-uploaded the cache was also out-of-date, so it refreshed itself, I guess.

**Pull request merged**
