### PR TITLE
Use language service instead of deprected add_lang on user

### PR DESCRIPTION
**Pull request by JulienTant**
Hi,

`add_lang` & `add_lang_ext` will be removed in 2.3.3, so the object of that pull request is to use the new recommended way of loading languages.

### CODE REVIEW

**Comment by rxu** [comment]
Tests fail due to indentation issues (tabs vs spases).

**Comment by JulienTant** [comment]
This is fixed! :)

**Comment by JulienTant** [comment]
up?

**Comment by rxu** [comment]
Thanks. Could you please leave the constructors docblock indentations as is but just add a string for the ```language``` param?

**Comment by Galixte** [comment]
@JulienTant any news?

**Comment by rxu** [comment]
Closed #98 via 9b2ad277eacb5c57a8b00cd254fb7e03fd72538c.

**Pull request closed without merging**
