### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by phpbb-es**
Spanish translation ;)

### CODE REVIEW

**Comment by rxu** [comment]
Tests failed https://travis-ci.org/rxu/thanks_for_posts/jobs/47416625

**Comment by rxu** [comment]
Fixed failing tests with 93de4495823333e73e818c0cae12684e90e109a3.

**Comment by phpbb-es** [comment]
Ohh, sorry rxu.

**Comment by rxu** [comment]
No problem, thanks :)

**Pull request merged**
