### PR TITLE
[FIX] Missing {L_COLON}

### PR DESCRIPTION
**Pull request by Galixte**
Hi,

about this issue: https://github.com/rxu/thanks_for_posts/issues/33

I propose this fix:
- Update for /styles/prosilver/template/event/viewtopic_body_postrow_custom_fields_after.html
- Update for /styles/prosilver/template/memberlist_view_thanks.html
- Update for /styles/subsilver2/template/event/viewtopic_body_postrow_custom_fields_after.html
- Update for /styles/subsilver2/template/memberlist_view_thanks.html

### CODE REVIEW

**Comment by rxu** [comment]
Thanks, but I'm pretty sure that the ```User Topic Count``` extension shouldn't be going into the infinite loop when more than 1 ```profile-posts``` element exists.

**Comment by Galixte** [comment]
This file ? https://github.com/marttiphpbb/phpbb-ext-usertopiccount/blob/master/styles/prosilver/template/viewtopic.js

This PR can be merged now ?

**Comment by Galixte** [comment]
Hi @rxu,

could you merge this PR ?

And take a look with @marttiphpbb to fix the infinite loop ?

**Comment by rxu** [comment]
I'm not really tending to change the class name for the ```thanks``` profile fields, as I think that is the User Topic Count extension issue (there shouldn't be any restrictions on using ```profile-posts``` class at all).

**Comment by Galixte** [comment]
And now could you merge this PR ? It fix some missing ```{L_COLON}```.

**Pull request merged**
